export const listData = [

  {id: 1, codigo: 'ISW014', nome: 'Projeto de Encontrabilidade', day: 'Segunda', time: '19:00-22:30', obj:'Explorar estratégias que direcionam o tráfego para um site, ajudam os usuários a encontrar conteúdo dentro de um site e encorajam consultas de retorno. Discutir os Métodos de Otimização de Search Engine (SEO), estratégias de marketing, análise de tráfego e teoria em torno comportamento de busca. Investigar as relações entre usabilidade, acessibilidade, arquitetura da informação, marketing, e encontrabilidade, a fim de implementar estratégias para a criação de conteúdo encontrável.', ementa: 'Teoria Geral. Marcação para encontrabilidade. Microformatos. Conteúdo. Rede Social. Estratégias Server-Side. Como evitar armadilhas de encontrabilidade. Pesquisas. Análises.'},
  {id: 2, codigo: 'ACI002', nome: 'Criação de Empresas para Internet', day: 'Terça', time: '19:00-20:40', obj: 'Fornecer ao estudante o estado da arte a respeito dos conhecimentos sobre empreendedorismo, inovação e criação de novos negócios para Internet.', ementa: 'O planejamento de um projeto de negócios para Internet. Implantação e implementação de projetos de negócios. Administração de custos e dos prazos de implantação em projetos. Identificação de oportunidades de investimentos. Analise de mercado. Desenvolvimento e implementação de negócios. Finanças de um projeto de Investimentos. Análise de sensibilidade. Empreendedorismo e inovação: liderança estratégica. Administração participativa e os novos modelos de administração. Principais funções administrativas e respectivos sistemas de informação. Mecanismos e procedimentos para criação de empresas. Criação de empresas focadas na Internet. Computação em Nuvem - estratégias e modelos. Formular e selecionar estratégias e modelos baseados em computação em nuvem. Análise dos pontos positivos e negativos dessa abordagem de negócios.'},
  {id: 3, codigo: 'ING012', nome: 'Inglês VI', day: 'Terça', time: '20:50-22:30', obj: 'Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas.', ementa: 'Aprimoramento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa.'},
  {id: 4, codigo: 'ISD002', nome: 'Arquitetura Orientada a Serviços', day: 'Quarta', time: '19:00-22:30', obj: 'Discutir tecnologias associadas a SOA (Services Oriented Architecture)', ementa: 'Construção de aplicações por meio da utilização de arquitetura orientada a serviços – SOA (Service-Oriented Architecture) e das principais tecnologias Web Services.'},
  {id: 5, codigo: 'ITE005', nome: 'Tópicos Especiais em Sistemas para Internet III', day: 'Quinta', time: '19:00-22:30', obj: 'Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.', ementa: 'Recursos e aplicações da tecnologia escolhida.'},
  {id: 6, codigo: 'ACI002', nome: 'Criação de Empresas para Internet', day: 'Sexta', time: '19:00-20:40', obj: 'Fornecer ao estudante o estado da arte a respeito dos conhecimentos sobre empreendedorismo, inovação e criação de novos negócios para Internet.', ementa: 'O planejamento de um projeto de negócios para Internet. Implantação e implementação de projetos de negócios. Administração de custos e dos prazos de implantação em projetos. Identificação de oportunidades de investimentos. Analise de mercado. Desenvolvimento e implementação de negócios. Finanças de um projeto de Investimentos. Análise de sensibilidade. Empreendedorismo e inovação: liderança estratégica. Administração participativa e os novos modelos de administração. Principais funções administrativas e respectivos sistemas de informação. Mecanismos e procedimentos para criação de empresas. Criação de empresas focadas na Internet. Computação em Nuvem - estratégias e modelos. Formular e selecionar estratégias e modelos baseados em computação em nuvem. Análise dos pontos positivos e negativos dessa abordagem de negócios.'},
  {id: 7, codigo: 'ITE004', nome: 'Tópicos Especiais em Sistemas para Internet II', day: 'Sexta', time: '19:00-22:30', obj: 'Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.', ementa: 'Recursos e aplicações da tecnologia escolhida.'},
  {id: 8, codigo: 'ISW013', nome: 'Desenvolvimento para Dispositivos Móveis II', day: 'Sábado', time: '13:30-17:00', obj: 'Discutir tecnologias de desenvolvimento de aplicativos para dispositivos móveis em alguma plataforma proprietária.', ementa: 'Uso de algum ambiente de desenvolvimento (framework) em plataforma proprietária: configuração do ambiente; emulação de dispositivos móveis nos computadores pessoais; interface gráfica; serviços disponíveis; banco de dados nos dispositivos. Desenvolvimento de aplicativos com uso de frameworks.'},
  
  
  ]